server:
  port: 9010
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          username: jiaxiwuli@126.com
          password: LIjiaxi118
          uri: https://gitee.com/lijiaxi118/blog-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
#management:
#  endpoints:
#    web:
#      expose: "*"

